#!/bin/sh

set -euo pipefail

# Check if toolctl is already installed
if command -v toolctl >/dev/null 2>&1; then
  echo '🎉 toolctl is already installed' >&2
  echo '💁 To get started with toolctl, run:'
  echo '     toolctl help'
  exit
fi

# Check if curl is installed
if ! [ -x "$(command -v curl)" ]; then
  echo 'Error: curl is not installed' >&2
  exit 1
fi

# Set the install directory
install_dir=~/.local/bin

# Check if the install directory exists
if ! [ -d ${install_dir} ]; then
  mkdir -p ${install_dir}
fi

# Get the current OS and architecture
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
arch=${arch/x86_64/amd64}

# Detect the latest version of toolctl
latest_version=$(
  curl -s https://raw.githubusercontent.com/toolctl/api/main/v0/toolctl/${os}-${arch}/meta.yaml |
    grep 'latest: ' |
    tr -d '[:space:]' |
    cut -d ':' -f 2
)

# Print the installation message
echo "👷 Installing toolctl v${latest_version} ..."

# Download and extract the latest version of toolctl to a temporary directory
tmp_dir=$(mktemp -d)
curl -s -L https://github.com/toolctl/toolctl/releases/download/v${latest_version}/toolctl_${latest_version}_${os}_${arch}.tar.gz |
 tar -xz -C "$tmp_dir"

# Move toolctl to the install directory
mv "$tmp_dir/toolctl" "${install_dir}/toolctl"

# Clean up
rm -rf "$tmp_dir"

# Check if toolctl was installed successfully
if [ $(${install_dir}/toolctl version --short) != ${latest_version} ]; then
  echo 'Error: Failed to install toolctl' >&2
  exit 1
fi
echo "🎉 Successfully installed at ${install_dir}/toolctl"

# Check if the install directory is in the PATH
if ! echo "${PATH}" | grep -q "${install_dir}"; then
  echo "💁 Please make sure to add ${install_dir} to your PATH"
  echo '💁 On macOS, you can run:'
  echo "     echo 'export PATH=${install_dir}:\$PATH' >> ~/.zshrc && . ~/.zshrc"
fi

# Print the usage message
echo '💁 To get started with toolctl, run:'
echo '     toolctl help'
